name: Tests sur PR de la branche dev

on:
  push:
    branches:
      - workflowsDev

jobs:
  test:
    name: 'Testing Flutter App'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.0.2
          cache: true

      - name: Install dependencies
        run: flutter pub get

      #- name: Analyze project source
      #  run: dart analyze

      - name: Run tests
        run: flutter test