name: Tests sur PR de la branche dev

on:
  push:
    branches:
      - workflowsDev

jobs:
  test:
    name: 'Testing Flutter App'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        flutter: ["stable"]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Run tests
        run: flutter test

      - name: Check test status
        id: test-result
        run: |
          if grep -q "All tests passed!" "$RUNNER_TEMP/test_output"; then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::failure"
          fi
      - name: Create pull request
        if: steps.test-result.outputs.status == 'success'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main
          title: "Merging changes from dev into main"
          body: |
            This pull request merges changes from the dev branch into the main branch.
      - name: Create rejected pull request
        if: steps.test-result.outputs.status == 'failure'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "rejected/${{ github.run_number }}"
          title: "Changes from dev branch were rejected"
          body: |
            This pull request contains changes that failed to pass the tests. Please review the changes and make necessary fixes before merging into the main branch.