name: Tests sur PR de la branche dev

on:
  push:
    branches:
      - workflowsDev

jobs:
  test:
    name: 'Testing Flutter App'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable # Utiliser la dernière version stable de Flutter
          # Si vous avez besoin de spécifier une version précise de Flutter, vous pouvez le faire en utilisant le paramètre "flutter-version"

      - name: Install dependencies
        run: flutter packages get # Exécuter la commande `flutter packages get` pour installer les dépendances

      - name: Run tests
        run: flutter test

  deploy-main:
    name: 'Deploy to main'
    runs-on: ubuntu-latest
    needs: [test]
    if: |
      always() && 
      (needs.test.result == 'success')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: workflowsDev
      - name: Deploy to workflowsDev
        run: |
          echo "# Config"
          git config --local user.email "[hidden]"
          git config --local user.name "CI"
          echo "# Fetch all"
          git fetch --all
          echo "# Checkout/pull development"
          git checkout workflowsDev
          git pull
          echo "# Checkout/pull master"
          git checkout workflows
          git pull
          echo "# Merge"
          git merge workflowsDev -X theirs --allow-unrelated-histories
          echo "# Push"
          git push origin
    
  deploy-rejected:
    name: 'Deploy to rejected build ${{ github.run_number }}'
    runs-on: ubuntu-latest
    needs: [test]
    if: |
      always() && 
      (needs.test.result == 'failure')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: workflowsDev
      - name: Deploy
        run: |
          echo "# Config"
          git config --local user.email "[hidden]"
          git config --local user.name "CI"
          git config --global pull.rebase true
          echo "# Fetch all"
          git fetch --all
          echo "# Checkout/pull development"
          git checkout workflowsDev
          git pull
          git checkout -b rejectedTESTCI/${{ github.run_number }}
          echo "# Merge"
          git merge workflowsDev -X theirs --allow-unrelated-histories
          git push origin rejectedTESTCI/${{ github.run_number }}
          echo "# Push"
          git checkout workflowsDev
          git reset --hard HEAD~1
          git push -f origin workflowsDev